from django.urls import path

from .views import (
    area_detail,
    areas,
    audit_forms,
    audit_form_detail,
    audits,
    audit_mobile_flow,
    audit_report_pdf,
    audit_report_puppeteer,
    branches,
    branch_detail,
    client_detail,
    clients,
    dashboard,
    dispensers,
    dispenser_detail,
    dispenser_models,
    health,
    incidents,
    incident_detail,
    incident_schedule_visit,
    csrf_token,
    login,
    notifications,
    nozzles,
    products,
    product_detail,
    register_fcm_token,
    user_detail,
    users,
    visits,
    visit_mobile_flow,
    visit_report_public_detail,
    visit_report_pdf,
    visit_report_puppeteer,
    visit_report_public_pdf,
)

urlpatterns = [
    path("health/", health, name="health"),
    path("csrf/", csrf_token, name="csrf_token"),
    path("login/", login, name="login"),
    path("dashboard/", dashboard, name="dashboard"),
    path("clients/", clients, name="clients"),
    path("clients/<int:client_id>/", client_detail, name="client_detail"),
    path("branches/", branches, name="branches"),
    path("branches/<int:branch_id>/", branch_detail, name="branch_detail"),
    path("areas/", areas, name="areas"),
    path("areas/<int:area_id>/", area_detail, name="area_detail"),
    path("dispensers/", dispensers, name="dispensers"),
    path("dispensers/<int:dispenser_id>/", dispenser_detail, name="dispenser_detail"),
    path("dispenser-models/", dispenser_models, name="dispenser_models"),
    path("nozzles/", nozzles, name="nozzles"),
    path("products/", products, name="products"),
    path("products/<int:product_id>/", product_detail, name="product_detail"),
    path("visits/", visits, name="visits"),
    path("audits/forms/", audit_forms, name="audit_forms"),
    path("audits/forms/<int:form_id>/", audit_form_detail, name="audit_form_detail"),
    path("audits/", audits, name="audits"),
    path("audits/<int:audit_id>/mobile-flow/", audit_mobile_flow, name="audit_mobile_flow"),
    path("audits/<int:audit_id>/report-puppeteer", audit_report_puppeteer, name="audit_report_puppeteer"),
    path("audits/<int:audit_id>/report-puppeteer.pdf", audit_report_puppeteer, name="audit_report_puppeteer_pdf"),
    path("audits/<int:audit_id>/report", audit_report_pdf, name="audit_report_legacy"),
    path("audits/<int:audit_id>/report/", audit_report_pdf, name="audit_report_legacy_slash"),
    path("audits/<int:audit_id>/report.pdf", audit_report_pdf, name="audit_report_legacy_pdf"),
    path("visits/<int:visit_id>/mobile-flow/", visit_mobile_flow, name="visit_mobile_flow"),
    path("visits/<int:visit_id>/report-puppeteer", visit_report_puppeteer, name="visit_report_puppeteer"),
    path("visits/<int:visit_id>/report-puppeteer.pdf", visit_report_puppeteer, name="visit_report_puppeteer_pdf"),
    path("visits/<int:visit_id>/report", visit_report_pdf, name="visit_report_legacy"),
    path("visits/<int:visit_id>/report/", visit_report_pdf, name="visit_report_legacy_slash"),
    path("visits/<int:visit_id>/report.pdf", visit_report_pdf, name="visit_report_legacy_pdf"),
    path("visits/report/public/<str:token>/", visit_report_public_detail, name="visit_report_public_detail"),
    path("visits/report/public/<str:token>.pdf", visit_report_public_pdf, name="visit_report_public_pdf"),
    path("incidents/", incidents, name="incidents"),
    path("notifications/", notifications, name="notifications"),
    path("register-fcm/", register_fcm_token, name="register_fcm_token"),
    path("incidents/<int:incident_id>/", incident_detail, name="incident_detail"),
    path("incidents/<int:incident_id>/schedule-visit/", incident_schedule_visit, name="incident_schedule_visit"),
    path("users/", users, name="users"),
    path("users/<int:user_id>/", user_detail, name="user_detail"),
]
