from django.urls import path

from .views import (
    areas,
    branches,
    client_detail,
    clients,
    dashboard,
    dispensers,
    health,
    incidents,
    login,
    products,
    user_detail,
    users,
    visits,
    visit_mobile_flow,
    visit_report_public_detail,
    visit_report_pdf,
    visit_report_public_pdf,
)

urlpatterns = [
    path("health/", health, name="health"),
    path("login/", login, name="login"),
    path("dashboard/", dashboard, name="dashboard"),
    path("clients/", clients, name="clients"),
    path("clients/<int:client_id>/", client_detail, name="client_detail"),
    path("branches/", branches, name="branches"),
    path("areas/", areas, name="areas"),
    path("dispensers/", dispensers, name="dispensers"),
    path("products/", products, name="products"),
    path("visits/", visits, name="visits"),
    path("visits/<int:visit_id>/mobile-flow/", visit_mobile_flow, name="visit_mobile_flow"),
    path("visits/<int:visit_id>/report", visit_report_pdf, name="visit_report_pdf_legacy"),
    path("visits/<int:visit_id>/report.pdf", visit_report_pdf, name="visit_report_pdf"),
    path("visits/report/public/<str:token>/", visit_report_public_detail, name="visit_report_public_detail"),
    path("visits/report/public/<str:token>.pdf", visit_report_public_pdf, name="visit_report_public_pdf"),
    path("incidents/", incidents, name="incidents"),
    path("users/", users, name="users"),
    path("users/<int:user_id>/", user_detail, name="user_detail"),
]
