# Generated by Django 5.2.11 on 2026-02-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="core.area"),
                ),
                (
                    "branch",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="core.branch"),
                ),
                (
                    "client",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="core.client"),
                ),
                (
                    "dispenser",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="core.dispenser"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "media_type",
                    models.CharField(choices=[("photo", "Foto"), ("video", "Video")], default="photo", max_length=20),
                ),
                ("file", models.FileField(upload_to="incidents/media/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "incident",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="core.incident"),
                ),
            ],
        ),
    ]
