# Generated by Django 5.2.11 on 2026-02-10 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_incident_incidentmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="visited_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
