# Generated by Django 5.2.11 on 2026-02-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="end_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="end_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="start_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="start_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Programada"),
                    ("in_progress", "En progreso"),
                    ("completed", "Finalizada"),
                    ("cancelled", "Cancelada"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="visit_report",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
