# Generated by Django 5.2.12 on 2026-03-12 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_visit_status_two_states"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_forms",
                        to="core.area",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("area", "name")},
            },
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Finalizada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("start_latitude", models.FloatField(blank=True, null=True)),
                ("start_longitude", models.FloatField(blank=True, null=True)),
                ("end_latitude", models.FloatField(blank=True, null=True)),
                ("end_longitude", models.FloatField(blank=True, null=True)),
                ("audit_report", models.JSONField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="core.area",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="core.auditform",
                    ),
                ),
            ],
            options={
                "ordering": ["-audited_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Foto"),
                            ("video", "Video"),
                            ("other", "Otro"),
                        ],
                        default="photo",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="audits/media/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.audit",
                    ),
                ),
            ],
        ),
    ]
