# Generated by Django 5.2.12 on 2026-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auditform_audit_auditmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="form_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="audit",
            name="form_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
