# Generated by Django 5.2.12 on 2026-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_audit_form_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepSeekAPISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                (
                    "model",
                    models.CharField(default="deepseek-reasoner", max_length=120),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DeepSeek API",
                "verbose_name_plural": "DeepSeek API",
            },
        ),
    ]
