# Generated by Django 5.2.12 on 2026-03-25 20:13

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_dispenser_products(apps, schema_editor):
    DispenserProductAssignment = apps.get_model("core", "DispenserProductAssignment")

    old_table = "core_dispenser_products"
    existing_tables = schema_editor.connection.introspection.table_names()
    if old_table not in existing_tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT dispenser_id, product_id FROM {old_table}")
        rows = cursor.fetchall()

    assignments = [
        DispenserProductAssignment(dispenser_id=dispenser_id, product_id=product_id)
        for dispenser_id, product_id in rows
    ]
    if assignments:
        DispenserProductAssignment.objects.bulk_create(assignments, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_dispenser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispenserProductAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispenser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_assignments",
                        to="core.dispenser",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispenser_assignments",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["dispenser__identifier", "product__name"],
                "unique_together": {("dispenser", "product")},
            },
        ),
        migrations.RunPython(copy_existing_dispenser_products, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="dispenser",
                    name="products",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="dispensers",
                        through="core.DispenserProductAssignment",
                        to="core.product",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name="Nozzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "dispensers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_nozzles",
                        to="core.dispenser",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dispenserproductassignment",
            name="nozzle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_assignments",
                to="core.nozzle",
            ),
        ),
    ]
