# Generated by Django 5.2.12 on 2026-03-25 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_dispenser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispenserProductAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispenser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_assignments",
                        to="core.dispenser",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispenser_assignments",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["dispenser__identifier", "product__name"],
            },
        ),
        migrations.AlterField(
            model_name="dispenser",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="dispensers",
                through="core.DispenserProductAssignment",
                to="core.product",
            ),
        ),
        migrations.CreateModel(
            name="Nozzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "dispensers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_nozzles",
                        to="core.dispenser",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dispenserproductassignment",
            name="nozzle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_assignments",
                to="core.nozzle",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dispenserproductassignment",
            unique_together={("dispenser", "product")},
        ),
    ]
