# Generated by Django 5.2.12 on 2026-03-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_dispenserproductassignment_alter_dispenser_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="dispenser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="core.dispenser",
            ),
        ),
    ]
