# Generated by Django 5.2.12 on 2026-03-30 15:13

from django.db import migrations, models


def seed_default_nozzles(apps, schema_editor):
    Nozzle = apps.get_model("core", "Nozzle")
    default_nozzles = [
        {"name": "Sin tip", "ml_per_liter_approx": 177.3, "percentage_approx": 17.7, "dilution_ratio_approx": "1:5.6"},
        {"name": "Grey (gris)", "ml_per_liter_approx": 171.0, "percentage_approx": 17.1, "dilution_ratio_approx": "1:5.9"},
        {"name": "Black (negro)", "ml_per_liter_approx": 160.1, "percentage_approx": 16.0, "dilution_ratio_approx": "1:6.3"},
        {"name": "Beige", "ml_per_liter_approx": 118.2, "percentage_approx": 11.8, "dilution_ratio_approx": "1:8.5"},
        {"name": "Red (rojo)", "ml_per_liter_approx": 75.3, "percentage_approx": 7.5, "dilution_ratio_approx": "1:13.3"},
        {"name": "White (blanco)", "ml_per_liter_approx": 49.4, "percentage_approx": 4.9, "dilution_ratio_approx": "1:20.2"},
        {"name": "Blue (azul)", "ml_per_liter_approx": 42.7, "percentage_approx": 4.3, "dilution_ratio_approx": "1:23.4"},
        {"name": "Clear Brown (marrón claro/transparente)", "ml_per_liter_approx": 31.8, "percentage_approx": 3.2, "dilution_ratio_approx": "1:31.5"},
        {"name": "Green (verde)", "ml_per_liter_approx": 19.0, "percentage_approx": 1.9, "dilution_ratio_approx": "1:52.6"},
        {"name": "Orange (naranja)", "ml_per_liter_approx": 14.6, "percentage_approx": 1.5, "dilution_ratio_approx": "1:68.5"},
        {"name": "Brown (marrón)", "ml_per_liter_approx": 12.5, "percentage_approx": 1.3, "dilution_ratio_approx": "1:80.0"},
        {"name": "Yellow (amarillo)", "ml_per_liter_approx": 10.4, "percentage_approx": 1.0, "dilution_ratio_approx": "1:96.2"},
        {"name": "Aqua", "ml_per_liter_approx": 8.3, "percentage_approx": 0.8, "dilution_ratio_approx": "1:120.5"},
        {"name": "Purple (morado)", "ml_per_liter_approx": 4.6, "percentage_approx": 0.5, "dilution_ratio_approx": "1:217.4"},
        {"name": "Pink (rosado)", "ml_per_liter_approx": 2.5, "percentage_approx": 0.3, "dilution_ratio_approx": "1:400", "is_ultra_lean_tip": True},
        {"name": "Lime (lima)", "ml_per_liter_approx": 2.1, "percentage_approx": 0.21, "dilution_ratio_approx": "1:476", "is_ultra_lean_tip": True},
        {"name": "Burgundy", "ml_per_liter_approx": 1.6, "percentage_approx": 0.16, "dilution_ratio_approx": "1:625", "is_ultra_lean_tip": True},
    ]

    for nozzle_data in default_nozzles:
        defaults = {
            "description": "Boquilla precargada para dosificación.",
            "ml_per_liter_approx": nozzle_data["ml_per_liter_approx"],
            "percentage_approx": nozzle_data["percentage_approx"],
            "dilution_ratio_approx": nozzle_data["dilution_ratio_approx"],
            "is_ultra_lean_tip": nozzle_data.get("is_ultra_lean_tip", False),
        }
        Nozzle.objects.update_or_create(name=nozzle_data["name"], defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_incident_dispenser"),
    ]

    operations = [
        migrations.AddField(
            model_name="nozzle",
            name="dilution_ratio_approx",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="nozzle",
            name="is_ultra_lean_tip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nozzle",
            name="ml_per_liter_approx",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="nozzle",
            name="percentage_approx",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.RunPython(seed_default_nozzles, migrations.RunPython.noop),
    ]
