# Generated by Django 5.2.13 on 2026-04-16 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_nozzle_dilution_ratio_approx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Configuración Principal", max_length=100),
                ),
                (
                    "archivo_json",
                    models.FileField(
                        help_text="Sube el JSON de la cuenta de servicio",
                        upload_to="secrets/",
                    ),
                ),
                (
                    "proyecto_id",
                    models.CharField(
                        help_text="ID del proyecto de Firebase", max_length=100
                    ),
                ),
                ("esta_activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuración Firebase",
                "verbose_name_plural": "Configuración Firebase",
            },
        ),
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_id", models.TextField(unique=True)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo FCM",
                "verbose_name_plural": "Dispositivos FCM",
            },
        ),
    ]
