# Generated by Django 5.2.11 on 2026-09-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_gmailapisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='general', max_length=80)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=30)),
                ('status', models.CharField(choices=[('pending_validation', 'Pendiente de validación'), ('in_director', 'En proceso'), ('completed', 'Resuelto'), ('rejected', 'Descartado')], default='pending_validation', max_length=40)),
                ('reporter_name', models.CharField(default='administrador', max_length=150)),
                ('reporter_email', models.CharField(blank=True, default='', max_length=150)),
                ('vida_ticket_id', models.IntegerField(blank=True, null=True)),
                ('vida_ticket_number', models.CharField(blank=True, default='', max_length=50)),
                ('attachments', models.TextField(default='[]')),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-id'],
            },
        ),
    ]
