# Generated by Django 5.2.11 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='target_system',
            field=models.CharField(
                choices=[('platform', 'Plataforma Web'), ('mobile', 'App Móvil'), ('both', 'Plataforma y Móvil')],
                default='platform',
                max_length=40
            ),
        ),
    ]
